// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5u_uLccqAggh8l7GHk3_3u-2LA8J7pzU',
    appId: '1:182864842471:web:e616c6c50e17d804e99c42',
    messagingSenderId: '182864842471',
    projectId: 'sus-hacks',
    authDomain: 'sus-hacks.firebaseapp.com',
    storageBucket: 'sus-hacks.appspot.com',
    measurementId: 'G-LVGM4E9G7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE_fsC5lG3in2QQTyseuVRvGNOGPrrtf4',
    appId: '1:182864842471:android:839fdb9d746e36e6e99c42',
    messagingSenderId: '182864842471',
    projectId: 'sus-hacks',
    storageBucket: 'sus-hacks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADhT5lgU3HKMquRhV4Rh-M02Pdpv01FjM',
    appId: '1:182864842471:ios:55d339f030376f8fe99c42',
    messagingSenderId: '182864842471',
    projectId: 'sus-hacks',
    storageBucket: 'sus-hacks.appspot.com',
    iosBundleId: 'com.example.prototype',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADhT5lgU3HKMquRhV4Rh-M02Pdpv01FjM',
    appId: '1:182864842471:ios:55d339f030376f8fe99c42',
    messagingSenderId: '182864842471',
    projectId: 'sus-hacks',
    storageBucket: 'sus-hacks.appspot.com',
    iosBundleId: 'com.example.prototype',
  );
}
